services:
  postgres:
    image: postgres:16-alpine
    container_name: maza-lojas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: maza_lojas
      POSTGRES_USER: maza
      POSTGRES_PASSWORD: maza
    ports:
      - "5432:5432"
    volumes:
      - maza_lojas_postgres_data:/var/lib/postgresql/data

volumes:
  maza_lojas_postgres_data:
