export const PRODUCTS = [
  {
    id: 1,
    category: "Piso Premium",
    title: "Tinta Piso Premium",
    description: "Produto indicado para pisos cimentados, que possui tecnologia nano flakes de Grafeno, proporcionando maior resistência e durabilidade.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/tinta-piso-premium",
    slug: "tinta-piso-premium",
  },
  {
    id: 2,
    category: "Esmalte Sintético",
    title: "Esmalte Sintético Standard",
    description: "Ideal para madeiras e metais, oferecendo excelente acabamento e proteção contra intempéries.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/esmalte-sintetico-standard",
    slug: "esmalte-sintetico-standard",
  },
  {
    id: 3,
    category: "Tinta Acrílica",
    title: "Tinta Acrílica Fosca",
    description: "Alta cobertura e rendimento, indicada para paredes internas e externas.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/tinta-acrilica-fosca",
    slug: "tinta-acrilica-fosca",
  },
  {
    id: 4,
    category: "Impermeabilizante",
    title: "Manta Líquida",
    description: "Proteção total contra infiltrações em lajes e telhados.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/manta-liquida",
    slug: "manta-liquida",
  },
  {
    id: 5,
    category: "Verniz",
    title: "Verniz Marítimo",
    description: "Proteção e brilho para madeiras expostas ao sol e chuva.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/verniz-maritimo",
    slug: "verniz-maritimo",
  },
  {
    id: 6,
    category: "Massa Corrida",
    title: "Massa Corrida PVA",
    description: "Fácil aplicação e lixamento, ideal para nivelar paredes internas.",
    image: "/assets/products/DiretoFerrugem.png",
    href: "/produto/massa-corrida-pva",
    slug: "massa-corrida-pva",
  },
];
